language: php

sudo: false

cache:
    directory:
        - $HOME/.composer/cache

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

install: composer update

before_script:
    - composer install --dev --no-interaction

script:
    - mkdir -p build/logs
    - phpunit -v

after_script:
    - php vendor/bin/coveralls

